### ISSUE TITLE
Guideline for New Contributors

### ISSUE THREAD

**Issue by fawad-sh** [William-McGonagle/burm#48]
The project is ❤️  interesting, I like to contribute however I am   🆕 to open source contribution but not to programming.

It will be helpful if you can add **code contribution guidelines** or point to some samples to give head start to  first timers.

Thanks 👍🏽  

**PS**: I saw so many beautiful software which does not reach the limelight because of lack of **use cases** and **good documentation**. The **Bun** seems amazing and the performance statistics on the [Bun.sh](https://bun.sh) are awesome 👀

**Comment by William-McGonagle** [comment]
Sure @fawad-sh, that sounds like a great idea!

**Comment by William-McGonagle** [comment]
Ok- we now have a CONTRIBUTING.md file
