### ISSUE TITLE
Code-style rules

### ISSUE THREAD

**Issue by fabianlanzerath** [William-McGonagle/burm#51]
👋🏼

I think it would be a good idea to have a prettier config or something similiar setup so that everyone who works on the codebase has the same style guides applied to it.

**Comment by William-McGonagle** [comment]
Sounds good- do you want to figurehead this initiative? Also it would be awesome if we followed the Airbnb Javascript style guide.

**Comment by fabianlanzerath** [comment]
Sure - I will do a PR.

**Comment by William-McGonagle** [comment]
Closed with #52
